os: osx
osx_image: xcode9.0

language: node_js
node_js: '8'
env:
  global:
  - DEBUG=electron-builder
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
script:
- sudo security list-keychains
- npm test
- npm run release
branches:
- master
- dev-2018
- certificates
notifications:
  slack: kestreltechnology:QcOSfR0bHUi92kqkmioIsT4H
